version: "3.8"

services:
  app1:
    image: nginx
    container_name: app1
    ports:
      - "8081:80"
    volumes:
      - ./demo/app1:/usr/share/nginx/html

  app2:
    image: nginx
    container_name: app2
    ports:
      - "8082:80"
    volumes:
      - ./demo/app2:/usr/share/nginx/html